Fixes and improvements for package installation during image builds
SSSD/sssd-ci-containers pull request #77
Opened 2024-02-25 01:36 UTC by dpward

These changes make image building more consistent between different distributions, by fixing discrepancies and re-using task lists where appropriate. (The task lists for RHEL now include those for CentOS; and the task lists for Ubuntu now include those for Debian.) This is intended to simply maintenance and allow for easier testing with other base images.

This also improves the build speed. Temporary volumes are now created and mounted at the paths where repository metadata is stored, so that it does not need to be re-downloaded for each image that is built (ipa, ldap, etc.) For Debian/Ubuntu, this metadata is now re-used across different package management operations for the same image.

Builds were performed successfully from these base images:

- registry.fedoraproject.org/fedora:{rawhide,40,latest}
- quay.io/centos/centos:{stream9,stream8}
- docker.io/library/debian:{unstable,testing,stable,oldstable}
- docker.io/library/ubuntu:{devel,rolling,latest}

2024-02-28 13:22 UTC, pbrezina commented
Wow, that's a lot of patches thank you. I'll let PR CI run and then review it if there is no major issue.

2024-03-01 10:43 UTC, pbrezina commented
Hmm, PR CI errors are not related to this pull request. It seems that some update started to cause issues when commiting to containers in the github runners. I need to look into it first.

2024-03-07 11:02 UTC, pbrezina commented
Hopefully, I fixed all PR CI issues, can you please rebase this pull request?

2024-03-18 12:18 UTC, jakub-vavra-cz requested changes
Removal of the groups without base_ prefix from when clauses will break downstream automation that depends on the simple names.
We are not using two inventories for installing packages and configuring services but a single one that has only the names like nfs, client...
We are installing and configuring  VMs so this split to layers does not make any sense there and makes the configuration needlessly complex and prone to issues.

2024-03-18 12:18 UTC, jakub-vavra-cz commented on src/ansible/roles/packages/tasks/Fedora.yml
> -- name: Select packageset
For testing we try to reduce the set of installed packages this is needed for
"Install extended set of packages"

2024-04-02 09:17 UTC, jakub-vavra-cz commented on src/ansible/roles/packages/tasks/Fedora.yml
> -  when: "'base_ldap' in group_names or 'ldap' in group_names or 'ipa' in group_names"
I am probably missing something, why would it be run twice and slow down the build?
When containers are built the phases for base with packages base_xxx are separate from the services so packages role is not executed again in services phase.
The inventory for VMs is already huge and complicated and we do not want it to be inflated by the extra groups like base_XXX.
I would rather see the whole base_XXX deal dropped and used just roles like ipa, ldap ./.. instead.

2024-04-15 10:46 UTC, pbrezina requested changes
Hi, thank you for the changes. Please, keep the group names as is at this moment. AFAIK the tasks are not run twice and it is needed so far. But it is certainly something we want to consolidate in the future.

2024-04-15 10:46 UTC, pbrezina commented on src/ansible/roles/facts/tasks/main.yml
> +- name: 'Include distribution specific tasks [{{ ansible_distribution }}]'
Please, keep the plugin. It may not be needed now, but it most certainly will be needed in the future.

2024-04-15 10:46 UTC, pbrezina commented on src/build.sh
> +rm --recursive --force "$SHARED_CACHE_ROOT"
This should go to cleanup?

2024-06-11 12:31 UTC, andreboscatto commented
Hi @dpward 

It has been a while since we left a few comments in this PR, will you be able to review those? If there is anything we can do to help, please let us know.

Kind regards

2025-08-25 10:38 UTC, pbrezina commented
Closing for inactivity.

2025-08-25 10:38 UTC, closed without merging