Install sssd-ldap package on IPA container
SSSD/sssd-ci-containers pull request #94
Opened 2024-05-01 13:19 UTC by liswang89

This PR is to resolve the issue encountered during the conversion of test_ldapapi to the new test framework.

In this feature, IPA, which stands for Identity Policy and Audit, serves as the upstream name. 389 operates as the backend, functioning as an LDAP server. To establish a connection to the LDAP database over a UNIX socket, it is necessary to install the sssd.ldap package on the IPA host.

2024-05-01 16:39 UTC, danlavu commented
The 389 sssd client isn't configured on the ldap container, so we decided to use the ipa container for testing instead. Lisa is working on a test case automation, multihost/basic/test_ldapapi.py  where sssd connects using ldapi protocol (UNIX socket) instead of TCP. So this needs to be executed on the server, with sssd configured using the ldap provider, that is why the package needs to be installed. 

@liswang89 , I do think we should create another task to install client packages on the IPA server, since the task is called install IPA. You also want to check Ubuntu and Debian yml files because they will require the package to be installed as well. The package names will likely not be the same, please confirm the package name for the proper distros.

2024-05-01 17:00 UTC, danlavu requested changes
Please create a new task similar to this one but name it "Install test dependencies on IPA server"

And do the following for Ubuntu and Debian, please.

2024-05-01 19:18 UTC, liswang89 commented
@danlavu Thank you for your comments. A task was created to address the issue, and the PR has been updated accordingly.

https://issues.redhat.com/projects/SSSD/issues/SSSD-7358

2024-05-07 05:01 UTC, jakub-vavra-cz commented
Hi, didn't test_ldapapi use local ldap on the client? Wouldn't it make more sense to run this in ldap container/vm instead?

2024-05-07 12:44 UTC, danlavu commented
> Hi, didn't test_ldapapi use local ldap on the client? Wouldn't it make more sense to run this in ldap container/vm instead?

That means we'd have to install 389 on the client. LDAPI connects over a UNIX socket, so it must be tested on the same host as 389.

2024-05-07 13:12 UTC, jakub-vavra-cz commented
> > Hi, didn't test_ldapapi use local ldap on the client? Wouldn't it make more sense to run this in ldap container/vm instead?
> 
> That means we'd have to install 389 on the client. LDAPI connects over a UNIX socket, so it must be tested on the same host as 389.

LDAPI connects to ldap not to IPA that's why I am asking why not use ldap container instead.

2024-05-07 20:17 UTC, liswang89 commented
@jakub-vavra-cz Since the client is not configured for LDAP, it would be easier to install the dependencies from IPA.

2024-05-10 10:37 UTC, pbrezina commented
We can also install 389ds on the client container, no problem there. It would require more simple sssd configuration then using ldap provider with ipa.

2024-06-03 17:41 UTC, closed without merging